### ISSUE TITLE
D6 and D7 versions of the module copied from Drupal.org as releases in github

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/ckeditor#1]
https://github.com/backdrop-contrib/ckeditor/releases

Was this intentional? I don't think the rest of the Backdrop contrib modules did that. These seem to be Drupal specific versions and having them in the GitHub repository might falsely lead people to believe they work with Backdrop. Should be removed.

**Comment by Graham-72** [comment]
Not intentional, so I have removed them all.

**Comment by klonos** [comment]
Lets close this then.
