### ISSUE TITLE
Setting Editor CSS to Use theme CSS generates a fatal error

### ISSUE THREAD

**Issue by vtad** [backdrop-contrib/ckeditor#2]
Fatal error: Call to a member function load() on a non-object in /home/www/backdrop/core/includes/theme.inc on line 1415

and then calling config generates
Warning: Illegal offset type in isset or empty in theme_get_setting() (line 1413 of /home/www/backdrop/core/includes/theme.inc).
... more notices and warnings
...

**Comment by quicksketch** [comment]
It sounds like the $theme variable that is being passed into this function is not a string. Perhaps CKEditor is calling `theme_get_setting()` with an array or object for the `$theme` parameter?

**Comment by quicksketch** [comment]
This is probably the issue:

```
// Grab stylesheets from color module
$color_paths = theme_get_setting('color_' . $current_theme . '_stylesheets', array());
```

That second parameter should just be dropped. In Drupal 7, the second parameter was the default and the third parameter was the theme name. In Backdrop, the default no longer needs to be provided (it's always populated by the .info file), so the second parameter was dropped.

**Comment by Graham-72** [comment]
Thanks @quicksketch. I have done this on my test site and the problem is fixed. Great!

**Comment by quicksketch** [comment]
You're welcome! Thanks for doing this port. :smile:

**Comment by klonos** [comment]
Fixed. Right?
