### ISSUE TITLE
Ready for official release?

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/ckeditor#6]
@quicksketch is it OK if I make an official release of this? I think it would be good to have this ready for Backdrop 1.1.x

**Comment by quicksketch** [comment]
Hi @Graham-72! Yes that would be great. The recent addition of Token module (and soon to be Pathauto) has given us a mechanism to move a module into core and disable the contrib version, however it will probably need to be elaborated to support replacing a module with the same name. But I think it would a good idea to make this publicly available asap to the existing users. We'll solve the problem for core when we get to it.

**Comment by serundeputy** [comment]
:+1:

**Comment by klonos** [comment]
First release was created. Please add `type=module` in the .info though.

**Comment by Graham-72** [comment]
Type=module now added

**Comment by klonos** [comment]
Thanx @Graham-72 :+1:

**Comment by Graham-72** [comment]
> After resolving the below errors, create another release to try packaging again.

@klonos When I create another release should I give it a new number eg. 1.x-1.16.1

**Comment by klonos** [comment]
If the only change that you made is the `type=module`, then I believe you can get away with not incrementing release number.

**Comment by Graham-72** [comment]
@klonos Thanks for the reply. To tidy things up and avoid the 'PACKAGING_ERROR_LOG.txt' (see below) I think perhaps I should try incrementing the version and release number and see what happens.
![releases backdrop-contrib-ckeditor 2015-05-04 20-26-12](https://cloud.githubusercontent.com/assets/10559274/7460588/ecbe684a-f29b-11e4-83b4-7bce67b71b23.png)

**Comment by Graham-72** [comment]
I have now produced release 1.x-1.16.1 as, hopefully, a tidy version.

**Comment by klonos** [comment]
No packaging error log. Good news! :wink:

**Comment by quicksketch** [comment]
Nice one @Graham-72!
